spring.application.name=JobProcessingPipeline
spring.datasource.url=jdbc:postgresql://localhost:5432/jobdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.auth.jwt.issuer=JobProcessingPipeline
app.auth.jwt.secret-base64=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
app.auth.jwt.expiration-seconds=3600
